### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by Ken-B** [JuliaIO/CodecXz.jl#12]
Not a bug or issue, but I just wanted to say thank you for this package! 

For reference, I read a compressed csv file as such:
```
using CodecXz, Queryverse
df = open(XzDecompressorStream, filename) do stream
    DataFrame(load(Stream(format"CSV", stream)))
end
```

Thanks again! 
cheers
(feel free to close ;)

**Comment by bicycle1885** [comment]
My pleasure! Let me close this issue to keep track of important stuff.
